version: 2
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  
jobs:
  maven/test:
    docker:
    - image: cimg/openjdk:8.0.275
    steps:
    - checkout
    - run:
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
        name: Generate Cache Checksum
        working_directory: $CIRCLE_WORKING_DIRECTORY/
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline "$@"
        name: Install Dependencies
        working_directory: ''
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn package "$@"
        name: Run package
        working_directory: ''
    - store_artifacts:
        path: target
    #- run: java -jar target/spring-boot-0.0.1-SNAPSHOT.jar
                        
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn verify "$@"
        name: Run Tests
        working_directory: ''
    - save_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
        paths:
        - ~/.m2/repository
    - store_test_results:
        path: target/surefire-reports
  s3/copy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
    - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: target
          to: 's3://spring-boot-xyz/app/'
    - aws-s3/copy:
          arguments: '--dryrun'
          from: target/spring-boot-0.0.1-SNAPSHOT.jar
          to: 's3://spring-boot-xyz'
workflows:
  version: 2
  Benchmarking Automation:
    jobs:
    - maven/test
    - s3/copy
