version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: circleci-ecr-orb-demo
          # $CIRCLE_BUILD_NUM
          tag: "latest, $CIRCLE_SHA1"
         
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          no-output-timeout: 20m
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: AWS_REGION_ENV_VAR_NAME
          repo: myECRRepository
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'