version: 2.0
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.275
        # circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
            
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - run: mvn clean install -Dmaven.test.skip=true
      
      - persist_to_workspace:
         root: ./
         paths:
           - target/

workflows:
  version: 2

  build-wf:
    jobs:
      - build
  build_and_push_image:
    jobs:  
      - aws-ecr/build-and-push-image:
          repo: $ECR_REPO_NAME
          extra-build-args: --force-rm
          tag: "latest,$CIRCLE_SHA1"
          attach-workspace: true
