version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
    
jobs:
  build:
    working_directory: ~/spring-project/app
    docker:
      - image: cimg/openjdk:8.0.275
    
    steps:
    - checkout
    - attach_workspace:
         at: ~/spring-project/app
    - run:
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
        name: Generate Cache Checksum
        
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline "$@"
        name: Install Dependencies
        
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn package "$@"
        name: Run package
        
    #- store_artifacts:
    #    path: target
    #- run: java -jar target/spring-boot-0.0.1-SNAPSHOT.jar
    - persist_to_workspace:
          root: ~/spring-project/app
          paths: ~/spring-project/app
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn verify "$@"
        name: Run Tests
        
    - save_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
        paths:
        - ~/.m2/repository
    - store_test_results:
        path: target/surefire-reports
        
  storeToSimple:
    working_directory: ~/spring-project/app
    docker:
      - image: 'cimg/python:3.9'
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/spring-project/app
      - run: ls
      - aws-s3/sync:
          arguments: '--delete'
          from: '~/spring-project/app/target/spring-boot-0.0.1-SNAPSHOT.jar'
          to: 's3://spring-boot-xyz/app/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: '~/spring-project/app/target/spring-boot-0.0.1-SNAPSHOT.jar'
          to: 's3://spring-boot-xyz'
workflows:
  version: 2
  push2S3:
    jobs:
    - build
    - storeToSimple:
        requires:
         - build
