version: 2
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  
executors:
  exe_openjdk:
    docker:
      - image: 'cimg/openjdk:8.0.275'
    working_directory: /mnt/spring-project/app

  python-aws-cli:
    docker:
      - image: 'cimg/python:3.6'
    working_directory: /mnt/spring-project/app
    
jobs:
  maven/test:
    executor: exe_openjdk
    steps:
    - checkout
    - attach_workspace:
         at: ~/spring-project
    - run:
        command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
        name: Generate Cache Checksum
        
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline "$@"
        name: Install Dependencies
        
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn package "$@"
        name: Run package
        
    #- store_artifacts:
    #    path: target
    #- run: java -jar target/spring-boot-0.0.1-SNAPSHOT.jar
    - persist_to_workspace:
          root: .
          paths: .
    - run:
        command: |
          if [ -n "" ]; then
            set -- "$@" --settings ""
          fi
          mvn verify "$@"
        name: Run Tests
        working_directory: ''
    - save_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
        paths:
        - ~/.m2/repository
    - store_test_results:
        path: target/surefire-reports
  s3/copy:
    executor: python-aws-cli
    steps:
    - attach_workspace:
          at: /mnt/spring-project/app
    - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: target
          to: 's3://spring-boot-xyz/app/'
    - aws-s3/copy:
          arguments: '--dryrun'
          from: /mnt/spring-project/app/target/spring-boot-0.0.1-SNAPSHOT.jar
          to: 's3://spring-boot-xyz'
workflows:
  version: 2
  push2S3:
    jobs:
    - maven/test
    - s3/copy:
        requires:
         - maven/test
