version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
            
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - run: mvn clean install -Dmaven.test.skip=true
      
      - persist_to_workspace:
         root: ./
         paths:
           - target/

workflows:
  version: 2

  build-wf:
    jobs:
      - build